### ISSUE TITLE
file upload process

### ISSUE THREAD

**Issue by halfbug** [halfbug/wsapi#1]

**Comment by halfbug** [comment]
please add "All" button in filter.

**Comment by Ammarah-khan** [comment]
On File List page? Or File upload page? what will this button do?

**Comment by halfbug** [comment]
on file list page with other filters "admin, sadmin" it will again display all records

**Comment by Ammarah-khan** [comment]
User Dropdown already present, fill that with these "admin,sadmin,all" values? or separate buttons like on user list page?

**Comment by Ammarah-khan** [comment]
This is User list filter - done there
