### ISSUE TITLE
package creating form

### ISSUE THREAD

**Issue by halfbug** [halfbug/wsapi#2]

**Comment by halfbug** [comment]
things to do in view
1.The create date should be start date
2.The both date fields should show calendar
3. Add new button for discount.
4. status should be enabled by default.

**Comment by fazzyA** [comment]
yes got it.. poora package add wala kaam krke ek 7 commit krdungi.

**Comment by fazzyA** [comment]
ill do it.. coding is done. ive asked asma to make me add discount button to show div..

**Comment by halfbug** [comment]
is it done and tested ?
i am getting this when try to add new package with new discount : 
`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'discount_id' cannot be null (SQL: insert into `packages` (`name`, `description`, `start_date`, `end_date`, `files_count`, `reset_count`, `price`, `discount_id`, `status`, `updated_at`, `created_at`) values (premium, <p>a premium pack</p>, 2017-06-16 11:57:14, 2017-06-16 11:57:14, 3, 4, 3432, , 1, 2017-06-16 23:58:37, 2017-06-16 23:58:37))`

**Comment by fazzyA** [comment]
ok im checking it add package bug n then update

**Comment by fazzyA** [comment]
SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'files_count' at row 1 (SQL: insert into `packages` (`name`, `description`, `start_date`, `end_date`, `files_count`, `reset_count`, `price`, `discount_id`, `status`, `updated_at`, `created_at`) values (premium, &lt;p&gt;prfemium apck&lt;/p&gt;, 2017-06-18 06:30:11, 2018-06-18 06:30:11, 3000, , 2000, 2, 1, 2017-06-18 06:38:39, 2017-06-18 06:38:39))

**Comment by fazzyA** [comment]
ye error kyun arha ha.. file ki range kam hai

**Comment by fazzyA** [comment]
ek dafa table structure dekh lena.. small integar krdungi aur reset count kiya hai.. wo tinyint thk hai ya wo b change hoga

**Comment by fazzyA** [comment]
ive committed aur table fields dekh k btado k sahi hai k nahi.. aur coding thek hai ya standard kis tarah improve hoga.. ubhi to kaam to kar raha ha

**Comment by fazzyA** [comment]
ye wala script add package and edit package pe laga k calender use kar lun??? 

ya kahi aur ye lines add hoti hai. main layout k page me

 <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  $( function() {
    $( "#datepicker" ).datepicker();
  } );
  </script>

**Comment by halfbug** [comment]
do not add in layout page. just add under script section on same edit/add page

**Comment by halfbug** [comment]
discount form has disturb alignment plus add some space on top.

**Comment by halfbug** [comment]
the discount type field is numeric only here a input filed is give.
add discount type as dropdown and the values are { 1=> monthly, 3=>one time,}

**Comment by halfbug** [comment]
calendar is missing  in both discount and package form

**Comment by fazzyA** [comment]
ok got it and working

**Comment by fazzyA** [comment]
add discount type as dropdown and the values are { 1=> monthly, 3=>one time,}

3=>one time hai ya 2 hoga

**Comment by fazzyA** [comment]
calender lagane par 6/21/2017 likh ata hai. error show horaha
![capture](https://user-images.githubusercontent.com/7613167/27387322-d7da0408-56b1-11e7-9ab5-ff001ea77675.PNG)

**Comment by fazzyA** [comment]
2017-06-18 08:02:52 is tarah already hai db me

**Comment by halfbug** [comment]
1.see the calender control documentation and try to change the date format resemble to the database.
or
2. reformat date on saving in your store aciton : 
`public function store(Request $request) {
		 ..
..
..
		  $package->start_date= date("d-M-Y h:i:s",strtotime($request->createdate));
		  $package->end_date= date("d-M-Y h:i:s",strtotime($request->enddate));
... .. .`

**Comment by halfbug** [comment]
ok done
