### ISSUE TITLE
Processed file upload process

### ISSUE THREAD

**Issue by halfbug** [halfbug/wsapi#23]
1. make file link click able on file list.
2. open file detail view having file name and meta data fields also requested file format ( currently only file name is in database rest is in pending).
3. give a button on top upload processed file ( only for admin user/ super admin  )
4. processed file open a modal form with browse file field and a upload button( submit button). see : (the bootstrap style and script already include to the layout you just need to add html in page)
https://www.w3schools.com/bootstrap/bootstrap_modal.asp
5. on upload button click upload file, new entry to database file table with the status processed and parent_id = uploaded file id.
5.1 Also change the status of uploaded file from inprogress to processed.
6. add a parent_id field in a database file table.
` Schema::table('files', function($table) {
            $table->integer("parent_id")->unsigned()->index()->nullable();
            $table->foreign("parent_id")->references('id')->on('files')->onDelete('cascade');
        });`
7. redirect after upload to file/list
8. list only display the files having parent_id = null.
9. add a column processed in file list. it will give a link to processed file.

**Comment by Ammarah-khan** [comment]
Need clarity on Point#9:
File list already has a download option in column "Action" which will link the user to the processed file.
1) Still should i provide this column "Processed"? 
2) If yes, then what will clicking on this link do?

**Comment by halfbug** [comment]
yes add a processed column and do the same actions just as we did in uploaded file download page.
1. on link click open a new page
2. similar page as earlier we use for uploaded file. just change the text accordingly.
3. on page load do following  :

- [ ] update file status to downloaded

- [ ] start downloading of  file
