### ISSUE TITLE
Edit / Upadate package.

### ISSUE THREAD

**Issue by halfbug** [halfbug/wsapi#5]
use same view (create.blade.php) to edit package. two actions will be added in controller 

1. "edit" function to load form for the specific package.
2. "update" function to save the changes.

**Comment by fazzyA** [comment]
ye task samajh nahi aya..

**Comment by halfbug** [comment]
jis terha package create kiya hai iss hi terha package edit bhi ker na hoga

**Comment by fazzyA** [comment]
check it please n tell me if it is ok..
